### PR TITLE
setting position fixed for nav bar

### LINKED ISSUE #69: Sticky nav bar

### PR DESCRIPTION
**Pull request by halimahexe**
## Description
I've set the position: fixed for nav bar so it moves with scroll.

## Related Issue
Closes #69

## How Can This Be Tested?
1. Run `npm install`
2. Run `npm run dev`
3. Navigate to http://localhost:5173 and scroll
4. The nav bar will cover some of the content. To fix this add the following className to the container of your main content: `pt-28`.
5. Check again and it should look perfect!

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings, including `` npm run build ``
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by halimahexe** [comment]
Also just fixed the double tabbing of links on nav bar.

File: src/components/NavBar/NavBar.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ function NavBar() {
 	const [isLoggedIn, setLogIn] = useState(false);
 
 	return (
-		<div className='w-full flex items-center justify-between p-4'>
+		<div className='w-full flex items-center justify-between p-4 fixed top-0 bg-white z-10'>
```
Comment (diddydeeable) [inline src/components/NavBar/NavBar.tsx:25]: interesting - why did you need a z-index - just curious as i've never used it before!

**Review by diddydeeable — APPROVED** [review]
